/***************************************************************
 *                                                             *
 *                   DO NOT MODIFY THIS FILE                   *
 *                                                             *
 * This file was generated by the flocoge tool. Any changes in *
 * this file will be lost on next file generation.             *
 * Generated by: flocoge-0.0.1                                 *
 * Generated on: 2015-10-18 23:47:39 +0200                     *
 ***************************************************************/

package pl.dpawlak.flocoge.diagram;


public class MergePointsFacade {

    private final MergePoints mergePoints;
    private final MergePointsExternal mergePointsExternal;

    public MergePointsFacade(MergePoints mergePoints, MergePointsExternal mergePointsExternal) {
        this.mergePoints = mergePoints;
        this.mergePointsExternal = mergePointsExternal;
    }

    public void inspectNode() {
        if (mergePoints.idInNode()) {
            if (mergePoints.indexInNode()) {
                if (mergePoints.allBranchesEqual()) {
                    mergePoints.loopDetected();
                    mergePoints.markInvalid();
                } else {
                }
            } else {
                if (mergePoints.mergePointExistsForThisIndex()) {
                    mergePoints.saveIndexInNode();
                } else {
                    saveMergePoint();
                }
            }
        } else {
            mergePoints.saveDecisionIdInNode();
        }
    }

    private void saveMergePoint() {
        if (mergePoints.otherMergePointExists()) {
            if (mergePoints.sameMergePoint()) {
                mergePoints.saveMergePointForBranch();
            } else {
                mergePoints.improperBranchingDetected();
                mergePoints.markInvalid();
            }
        } else {
            mergePoints.saveMergePointOnBothBranches();
        }
    }

}
