/***************************************************************
 *                                                             *
 *                   DO NOT MODIFY THIS FILE                   *
 *                                                             *
 * This file was generated by the flocoge tool. Any changes in *
 * this file will be lost on next file generation.             *
 * Generated by: flocoge-0.0.1                                 *
 * Generated on: 2015-10-18 23:47:39 +0200                     *
 ***************************************************************/

package pl.dpawlak.flocoge.diagram;


public interface MergePointsExternal {


}
